# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BarleyBreakSettingsWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1090, 665)
        Form.setStyleSheet("background-color: rgb(149, 181, 255);")
        self.settings_label = QtWidgets.QLabel(Form)
        self.settings_label.setGeometry(QtCore.QRect(360, 50, 481, 121))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(36)
        self.settings_label.setFont(font)
        self.settings_label.setAlignment(QtCore.Qt.AlignCenter)
        self.settings_label.setObjectName("settings_label")
        self.back_btn = QtWidgets.QPushButton(Form)
        self.back_btn.setGeometry(QtCore.QRect(50, 60, 191, 111))
        self.back_btn.setText("")
        self.back_btn.setObjectName("back_btn")
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(260, 190, 581, 161))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.speed_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(20)
        self.speed_label.setFont(font)
        self.speed_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.speed_label.setObjectName("speed_label")
        self.gridLayout.addWidget(self.speed_label, 0, 0, 1, 1)
        self.language_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(20)
        self.language_label.setFont(font)
        self.language_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.language_label.setObjectName("language_label")
        self.gridLayout.addWidget(self.language_label, 1, 0, 1, 1)
        self.speed_spin_box = QtWidgets.QSpinBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(20)
        self.speed_spin_box.setFont(font)
        self.speed_spin_box.setMinimum(1)
        self.speed_spin_box.setMaximum(10)
        self.speed_spin_box.setProperty("value", 3)
        self.speed_spin_box.setObjectName("speed_spin_box")
        self.gridLayout.addWidget(self.speed_spin_box, 0, 1, 1, 1)
        self.language_comboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        self.language_comboBox.setFont(font)
        self.language_comboBox.setStyleSheet("")
        self.language_comboBox.setObjectName("language_comboBox")
        self.gridLayout.addWidget(self.language_comboBox, 1, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Settings"))
        self.settings_label.setText(_translate("Form", "Settings"))
        self.speed_label.setText(_translate("Form", "Speed"))
        self.language_label.setText(_translate("Form", "Language"))
