# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StartScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_Start(object):
    def setupUi(self, MainWindow_Start):
        MainWindow_Start.setObjectName("MainWindow_Start")
        MainWindow_Start.resize(1063, 685)
        self.centralwidget = QtWidgets.QWidget(MainWindow_Start)
        self.centralwidget.setStyleSheet("background-color: rgb(149, 181, 255);")
        self.centralwidget.setObjectName("centralwidget")
        self.background_label = QtWidgets.QLabel(self.centralwidget)
        self.background_label.setGeometry(QtCore.QRect(-20, -36, 1091, 741))
        self.background_label.setStyleSheet("background-color: rgb(149, 181, 255);")
        self.background_label.setText("")
        self.background_label.setObjectName("background_label")
        self.heading_label = QtWidgets.QLabel(self.centralwidget)
        self.heading_label.setGeometry(QtCore.QRect(410, 30, 281, 141))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(28)
        self.heading_label.setFont(font)
        self.heading_label.setAlignment(QtCore.Qt.AlignCenter)
        self.heading_label.setObjectName("heading_label")
        self.new_game_btn = QtWidgets.QPushButton(self.centralwidget)
        self.new_game_btn.setGeometry(QtCore.QRect(410, 210, 281, 111))
        self.new_game_btn.setText("")
        self.new_game_btn.setObjectName("new_game_btn")
        self.resume_game_btn = QtWidgets.QPushButton(self.centralwidget)
        self.resume_game_btn.setGeometry(QtCore.QRect(410, 350, 281, 111))
        self.resume_game_btn.setText("")
        self.resume_game_btn.setObjectName("resume_game_btn")
        self.settings_btn = QtWidgets.QPushButton(self.centralwidget)
        self.settings_btn.setGeometry(QtCore.QRect(410, 490, 281, 111))
        self.settings_btn.setText("")
        self.settings_btn.setObjectName("settings_btn")
        MainWindow_Start.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow_Start)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_Start)

    def retranslateUi(self, MainWindow_Start):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_Start.setWindowTitle(_translate("MainWindow_Start", "MainWindow"))
        self.heading_label.setText(_translate("MainWindow_Start", "15Puzzle"))
